use tonic::{metadata::MetadataValue, transport::Channel, Request};
pub mod deraine_pb {
    tonic::include_proto!("deraine"); // Generated by build.rs
}

use deraine_pb::deraine_service_client::DeraineServiceClient;
use deraine_pb::{SearchKnnRequest, WriteVectorRequest, GetEngineStatusRequest};

pub struct Client {
    inner: DeraineServiceClient<Channel>,
    api_key: String,
}

impl Client {
    /// Connects to a DeraineDB server. `api_key` must match the server's
    /// DERAINE_DB_API_KEY.
    pub async fn connect(dst: String, api_key: String) -> Result<Self, tonic::transport::Error> {
        let channel = Channel::from_shared(dst)?.connect().await?;
        Ok(Self {
            inner: DeraineServiceClient::new(channel),
            api_key,
        })
    }

    fn authorize<T>(&self, mut request: Request<T>) -> Request<T> {
        if let Ok(value) = MetadataValue::try_from(self.api_key.as_str()) {
            request.metadata_mut().insert("x-api-key", value);
        }
        request
    }

    pub async fn write(&mut self, id: u64, data: Vec<f32>, metadata_mask: u64) -> Result<(), tonic::Status> {
        let request = self.authorize(Request::new(WriteVectorRequest {
            id,
            data,
            metadata_mask,
        }));
        self.inner.write_vector(request).await?;
        Ok(())
    }

    pub async fn search(&mut self, query: Vec<f32>, k: u32, filter_mask: u64) -> Result<Vec<deraine_pb::SearchMatch>, tonic::Status> {
        let request = self.authorize(Request::new(SearchKnnRequest {
            query,
            k,
            filter_mask,
        }));
        let response = self.inner.search_knn(request).await?;
        Ok(response.into_inner().matches)
    }

    pub async fn get_status(&mut self) -> Result<deraine_pb::GetEngineStatusResponse, tonic::Status> {
        let request = self.authorize(Request::new(GetEngineStatusRequest {}));
        let response = self.inner.get_engine_status(request).await?;
        Ok(response.into_inner())
    }
}
