use tonic::{transport::Channel, Request};
pub mod deraine_pb {
    tonic::include_proto!("deraine"); // Generated by build.rs
}

use deraine_pb::deraine_service_client::DeraineServiceClient;
use deraine_pb::{SearchKnnRequest, WriteVectorRequest, GetEngineStatusRequest};

pub struct Client {
    inner: DeraineServiceClient<Channel>,
}

impl Client {
    pub async fn connect(dst: String) -> Result<Self, tonic::transport::Error> {
        let channel = Channel::from_shared(dst)?.connect().await?;
        Ok(Self {
            inner: DeraineServiceClient::new(channel),
        })
    }

    pub async fn write(&mut self, id: u64, data: Vec<f32>, mask: u64) -> Result<(), tonic::Status> {
        let request = Request::new(WriteVectorRequest {
            id,
            data,
            metadata_mask: mask,
        });
        self.inner.write_vector(request).await?;
        Ok(())
    }

    pub async fn search(&mut self, query: Vec<f32>, k: u32, mask: u64) -> Result<Vec<deraine_pb::SearchMatch>, tonic::Status> {
        let request = Request::new(SearchKnnRequest {
            query,
            k,
            filter_mask: mask,
        });
        let response = self.inner.search_knn(request).await?;
        Ok(response.into_inner().matches)
    }

    pub async fn get_status(&mut self) -> Result<deraine_pb::GetEngineStatusResponse, tonic::Status> {
        let request = Request::new(GetEngineStatusRequest {});
        let response = self.inner.get_engine_status(request).await?;
        Ok(response.into_inner())
    }
}
