// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/deraine.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	DeraineService_WriteVector_FullMethodName     = "/deraine.v1.DeraineService/WriteVector"
	DeraineService_SearchKNN_FullMethodName       = "/deraine.v1.DeraineService/SearchKNN"
	DeraineService_DeleteVector_FullMethodName    = "/deraine.v1.DeraineService/DeleteVector"
	DeraineService_CreateSnapshot_FullMethodName  = "/deraine.v1.DeraineService/CreateSnapshot"
	DeraineService_GetEngineStatus_FullMethodName = "/deraine.v1.DeraineService/GetEngineStatus"
	DeraineService_GetStats_FullMethodName        = "/deraine.v1.DeraineService/GetStats"
)

type DeraineServiceClient interface {
	WriteVector(ctx context.Context, in *WriteVectorRequest, opts ...grpc.CallOption) (*WriteVectorResponse, error)
	SearchKNN(ctx context.Context, in *SearchKNNRequest, opts ...grpc.CallOption) (*SearchKNNResponse, error)
	DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error)
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	GetEngineStatus(ctx context.Context, in *GetEngineStatusRequest, opts ...grpc.CallOption) (*GetEngineStatusResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type deraineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeraineServiceClient(cc grpc.ClientConnInterface) DeraineServiceClient {
	return &deraineServiceClient{cc}
}

func (c *deraineServiceClient) WriteVector(ctx context.Context, in *WriteVectorRequest, opts ...grpc.CallOption) (*WriteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteVectorResponse)
	err := c.cc.Invoke(ctx, DeraineService_WriteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deraineServiceClient) SearchKNN(ctx context.Context, in *SearchKNNRequest, opts ...grpc.CallOption) (*SearchKNNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKNNResponse)
	err := c.cc.Invoke(ctx, DeraineService_SearchKNN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deraineServiceClient) DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVectorResponse)
	err := c.cc.Invoke(ctx, DeraineService_DeleteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deraineServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, DeraineService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deraineServiceClient) GetEngineStatus(ctx context.Context, in *GetEngineStatusRequest, opts ...grpc.CallOption) (*GetEngineStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEngineStatusResponse)
	err := c.cc.Invoke(ctx, DeraineService_GetEngineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deraineServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, DeraineService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DeraineServiceServer interface {
	WriteVector(context.Context, *WriteVectorRequest) (*WriteVectorResponse, error)
	SearchKNN(context.Context, *SearchKNNRequest) (*SearchKNNResponse, error)
	DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error)
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	GetEngineStatus(context.Context, *GetEngineStatusRequest) (*GetEngineStatusResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedDeraineServiceServer()
}

type UnimplementedDeraineServiceServer struct{}

func (UnimplementedDeraineServiceServer) WriteVector(context.Context, *WriteVectorRequest) (*WriteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteVector not implemented")
}
func (UnimplementedDeraineServiceServer) SearchKNN(context.Context, *SearchKNNRequest) (*SearchKNNResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchKNN not implemented")
}
func (UnimplementedDeraineServiceServer) DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVector not implemented")
}
func (UnimplementedDeraineServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedDeraineServiceServer) GetEngineStatus(context.Context, *GetEngineStatusRequest) (*GetEngineStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEngineStatus not implemented")
}
func (UnimplementedDeraineServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedDeraineServiceServer) mustEmbedUnimplementedDeraineServiceServer() {}
func (UnimplementedDeraineServiceServer) testEmbeddedByValue()                        {}

type UnsafeDeraineServiceServer interface {
	mustEmbedUnimplementedDeraineServiceServer()
}

func RegisterDeraineServiceServer(s grpc.ServiceRegistrar, srv DeraineServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeraineService_ServiceDesc, srv)
}

func _DeraineService_WriteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).WriteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_WriteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).WriteVector(ctx, req.(*WriteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeraineService_SearchKNN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKNNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).SearchKNN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_SearchKNN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).SearchKNN(ctx, req.(*SearchKNNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeraineService_DeleteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).DeleteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_DeleteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).DeleteVector(ctx, req.(*DeleteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeraineService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeraineService_GetEngineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEngineStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).GetEngineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_GetEngineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).GetEngineStatus(ctx, req.(*GetEngineStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeraineService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var DeraineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deraine.v1.DeraineService",
	HandlerType: (*DeraineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteVector",
			Handler:    _DeraineService_WriteVector_Handler,
		},
		{
			MethodName: "SearchKNN",
			Handler:    _DeraineService_SearchKNN_Handler,
		},
		{
			MethodName: "DeleteVector",
			Handler:    _DeraineService_DeleteVector_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _DeraineService_CreateSnapshot_Handler,
		},
		{
			MethodName: "GetEngineStatus",
			Handler:    _DeraineService_GetEngineStatus_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _DeraineService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/deraine.proto",
}
