// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/deraine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchMode int32

const (
	SearchMode_SEARCH_FLAT SearchMode = 0
	SearchMode_SEARCH_HNSW SearchMode = 1
)

// Enum value maps for SearchMode.
var (
	SearchMode_name = map[int32]string{
		0: "SEARCH_FLAT",
		1: "SEARCH_HNSW",
	}
	SearchMode_value = map[string]int32{
		"SEARCH_FLAT": 0,
		"SEARCH_HNSW": 1,
	}
)

func (x SearchMode) Enum() *SearchMode {
	p := new(SearchMode)
	*p = x
	return p
}

func (x SearchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_deraine_proto_enumTypes[0].Descriptor()
}

func (SearchMode) Type() protoreflect.EnumType {
	return &file_proto_deraine_proto_enumTypes[0]
}

func (x SearchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchMode.Descriptor instead.
func (SearchMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{0}
}

type WriteVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MetadataMask  uint64                 `protobuf:"varint,2,opt,name=metadata_mask,json=metadataMask,proto3" json:"metadata_mask,omitempty"`
	Data          []float32              `protobuf:"fixed32,3,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteVectorRequest) Reset() {
	*x = WriteVectorRequest{}
	mi := &file_proto_deraine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteVectorRequest) ProtoMessage() {}

func (x *WriteVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteVectorRequest.ProtoReflect.Descriptor instead.
func (*WriteVectorRequest) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{0}
}

func (x *WriteVectorRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WriteVectorRequest) GetMetadataMask() uint64 {
	if x != nil {
		return x.MetadataMask
	}
	return 0
}

func (x *WriteVectorRequest) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteVectorResponse) Reset() {
	*x = WriteVectorResponse{}
	mi := &file_proto_deraine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteVectorResponse) ProtoMessage() {}

func (x *WriteVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteVectorResponse.ProtoReflect.Descriptor instead.
func (*WriteVectorResponse) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{1}
}

func (x *WriteVectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SearchKNNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryVector   []float32              `protobuf:"fixed32,1,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	K             uint32                 `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	FilterMask    uint64                 `protobuf:"varint,3,opt,name=filter_mask,json=filterMask,proto3" json:"filter_mask,omitempty"`
	Mode          SearchMode             `protobuf:"varint,4,opt,name=mode,proto3,enum=deraine.v1.SearchMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchKNNRequest) Reset() {
	*x = SearchKNNRequest{}
	mi := &file_proto_deraine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKNNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKNNRequest) ProtoMessage() {}

func (x *SearchKNNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKNNRequest.ProtoReflect.Descriptor instead.
func (*SearchKNNRequest) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{2}
}

func (x *SearchKNNRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *SearchKNNRequest) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchKNNRequest) GetFilterMask() uint64 {
	if x != nil {
		return x.FilterMask
	}
	return 0
}

func (x *SearchKNNRequest) GetMode() SearchMode {
	if x != nil {
		return x.Mode
	}
	return SearchMode_SEARCH_FLAT
}

type SearchKNNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchKNNResponse) Reset() {
	*x = SearchKNNResponse{}
	mi := &file_proto_deraine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKNNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKNNResponse) ProtoMessage() {}

func (x *SearchKNNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKNNResponse.ProtoReflect.Descriptor instead.
func (*SearchKNNResponse) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{3}
}

func (x *SearchKNNResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_proto_deraine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{4}
}

func (x *Match) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Match) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type DeleteVectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorRequest) Reset() {
	*x = DeleteVectorRequest{}
	mi := &file_proto_deraine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorRequest) ProtoMessage() {}

func (x *DeleteVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorRequest.ProtoReflect.Descriptor instead.
func (*DeleteVectorRequest) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteVectorRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorResponse) Reset() {
	*x = DeleteVectorResponse{}
	mi := &file_proto_deraine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorResponse) ProtoMessage() {}

func (x *DeleteVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorResponse.ProtoReflect.Descriptor instead.
func (*DeleteVectorResponse) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVectorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEngineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEngineStatusRequest) Reset() {
	*x = GetEngineStatusRequest{}
	mi := &file_proto_deraine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEngineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEngineStatusRequest) ProtoMessage() {}

func (x *GetEngineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEngineStatusRequest.ProtoReflect.Descriptor instead.
func (*GetEngineStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{7}
}

type GetEngineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	VectorCount   uint64                 `protobuf:"varint,3,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	IndexLevel    int32                  `protobuf:"varint,4,opt,name=index_level,json=indexLevel,proto3" json:"index_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEngineStatusResponse) Reset() {
	*x = GetEngineStatusResponse{}
	mi := &file_proto_deraine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEngineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEngineStatusResponse) ProtoMessage() {}

func (x *GetEngineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEngineStatusResponse.ProtoReflect.Descriptor instead.
func (*GetEngineStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{8}
}

func (x *GetEngineStatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *GetEngineStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetEngineStatusResponse) GetVectorCount() uint64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *GetEngineStatusResponse) GetIndexLevel() int32 {
	if x != nil {
		return x.IndexLevel
	}
	return 0
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPath    string                 `protobuf:"bytes,1,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_proto_deraine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSnapshotRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_proto_deraine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSnapshotResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_deraine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{11}
}

type GetStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VectorCount      uint64                 `protobuf:"varint,1,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	MemoryUsageBytes uint64                 `protobuf:"varint,2,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_deraine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deraine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_deraine_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatsResponse) GetVectorCount() uint64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *GetStatsResponse) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

var File_proto_deraine_proto protoreflect.FileDescriptor

const file_proto_deraine_proto_rawDesc = "" +
	"\n" +
	"\x13proto/deraine.proto\x12\n" +
	"deraine.v1\"]\n" +
	"\x12WriteVectorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rmetadata_mask\x18\x02 \x01(\x04R\fmetadataMask\x12\x12\n" +
	"\x04data\x18\x03 \x03(\x02R\x04data\"/\n" +
	"\x13WriteVectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x90\x01\n" +
	"\x10SearchKNNRequest\x12!\n" +
	"\fquery_vector\x18\x01 \x03(\x02R\vqueryVector\x12\f\n" +
	"\x01k\x18\x02 \x01(\rR\x01k\x12\x1f\n" +
	"\vfilter_mask\x18\x03 \x01(\x04R\n" +
	"filterMask\x12*\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x16.deraine.v1.SearchModeR\x04mode\"@\n" +
	"\x11SearchKNNResponse\x12+\n" +
	"\amatches\x18\x01 \x03(\v2\x11.deraine.v1.MatchR\amatches\"3\n" +
	"\x05Match\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"%\n" +
	"\x13DeleteVectorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"0\n" +
	"\x14DeleteVectorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x18\n" +
	"\x16GetEngineStatusRequest\"\x91\x01\n" +
	"\x17GetEngineStatusResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fvector_count\x18\x03 \x01(\x04R\vvectorCount\x12\x1f\n" +
	"\vindex_level\x18\x04 \x01(\x05R\n" +
	"indexLevel\"8\n" +
	"\x15CreateSnapshotRequest\x12\x1f\n" +
	"\vtarget_path\x18\x01 \x01(\tR\n" +
	"targetPath\"W\n" +
	"\x16CreateSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x11\n" +
	"\x0fGetStatsRequest\"c\n" +
	"\x10GetStatsResponse\x12!\n" +
	"\fvector_count\x18\x01 \x01(\x04R\vvectorCount\x12,\n" +
	"\x12memory_usage_bytes\x18\x02 \x01(\x04R\x10memoryUsageBytes*.\n" +
	"\n" +
	"SearchMode\x12\x0f\n" +
	"\vSEARCH_FLAT\x10\x00\x12\x0f\n" +
	"\vSEARCH_HNSW\x10\x012\xf9\x03\n" +
	"\x0eDeraineService\x12N\n" +
	"\vWriteVector\x12\x1e.deraine.v1.WriteVectorRequest\x1a\x1f.deraine.v1.WriteVectorResponse\x12H\n" +
	"\tSearchKNN\x12\x1c.deraine.v1.SearchKNNRequest\x1a\x1d.deraine.v1.SearchKNNResponse\x12Q\n" +
	"\fDeleteVector\x12\x1f.deraine.v1.DeleteVectorRequest\x1a .deraine.v1.DeleteVectorResponse\x12W\n" +
	"\x0eCreateSnapshot\x12!.deraine.v1.CreateSnapshotRequest\x1a\".deraine.v1.CreateSnapshotResponse\x12Z\n" +
	"\x0fGetEngineStatus\x12\".deraine.v1.GetEngineStatusRequest\x1a#.deraine.v1.GetEngineStatusResponse\x12E\n" +
	"\bGetStats\x12\x1b.deraine.v1.GetStatsRequest\x1a\x1c.deraine.v1.GetStatsResponseB+Z)github.com/ricardo/deraine-db/api/grpc/pbb\x06proto3"

var (
	file_proto_deraine_proto_rawDescOnce sync.Once
	file_proto_deraine_proto_rawDescData []byte
)

func file_proto_deraine_proto_rawDescGZIP() []byte {
	file_proto_deraine_proto_rawDescOnce.Do(func() {
		file_proto_deraine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deraine_proto_rawDesc), len(file_proto_deraine_proto_rawDesc)))
	})
	return file_proto_deraine_proto_rawDescData
}

var file_proto_deraine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_deraine_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_deraine_proto_goTypes = []any{
	(SearchMode)(0),                 // 0: deraine.v1.SearchMode
	(*WriteVectorRequest)(nil),      // 1: deraine.v1.WriteVectorRequest
	(*WriteVectorResponse)(nil),     // 2: deraine.v1.WriteVectorResponse
	(*SearchKNNRequest)(nil),        // 3: deraine.v1.SearchKNNRequest
	(*SearchKNNResponse)(nil),       // 4: deraine.v1.SearchKNNResponse
	(*Match)(nil),                   // 5: deraine.v1.Match
	(*DeleteVectorRequest)(nil),     // 6: deraine.v1.DeleteVectorRequest
	(*DeleteVectorResponse)(nil),    // 7: deraine.v1.DeleteVectorResponse
	(*GetEngineStatusRequest)(nil),  // 8: deraine.v1.GetEngineStatusRequest
	(*GetEngineStatusResponse)(nil), // 9: deraine.v1.GetEngineStatusResponse
	(*CreateSnapshotRequest)(nil),   // 10: deraine.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),  // 11: deraine.v1.CreateSnapshotResponse
	(*GetStatsRequest)(nil),         // 12: deraine.v1.GetStatsRequest
	(*GetStatsResponse)(nil),        // 13: deraine.v1.GetStatsResponse
}
var file_proto_deraine_proto_depIdxs = []int32{
	0,  // 0: deraine.v1.SearchKNNRequest.mode:type_name -> deraine.v1.SearchMode
	5,  // 1: deraine.v1.SearchKNNResponse.matches:type_name -> deraine.v1.Match
	1,  // 2: deraine.v1.DeraineService.WriteVector:input_type -> deraine.v1.WriteVectorRequest
	3,  // 3: deraine.v1.DeraineService.SearchKNN:input_type -> deraine.v1.SearchKNNRequest
	6,  // 4: deraine.v1.DeraineService.DeleteVector:input_type -> deraine.v1.DeleteVectorRequest
	10, // 5: deraine.v1.DeraineService.CreateSnapshot:input_type -> deraine.v1.CreateSnapshotRequest
	8,  // 6: deraine.v1.DeraineService.GetEngineStatus:input_type -> deraine.v1.GetEngineStatusRequest
	12, // 7: deraine.v1.DeraineService.GetStats:input_type -> deraine.v1.GetStatsRequest
	2,  // 8: deraine.v1.DeraineService.WriteVector:output_type -> deraine.v1.WriteVectorResponse
	4,  // 9: deraine.v1.DeraineService.SearchKNN:output_type -> deraine.v1.SearchKNNResponse
	7,  // 10: deraine.v1.DeraineService.DeleteVector:output_type -> deraine.v1.DeleteVectorResponse
	11, // 11: deraine.v1.DeraineService.CreateSnapshot:output_type -> deraine.v1.CreateSnapshotResponse
	9,  // 12: deraine.v1.DeraineService.GetEngineStatus:output_type -> deraine.v1.GetEngineStatusResponse
	13, // 13: deraine.v1.DeraineService.GetStats:output_type -> deraine.v1.GetStatsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_deraine_proto_init() }
func file_proto_deraine_proto_init() {
	if File_proto_deraine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deraine_proto_rawDesc), len(file_proto_deraine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deraine_proto_goTypes,
		DependencyIndexes: file_proto_deraine_proto_depIdxs,
		EnumInfos:         file_proto_deraine_proto_enumTypes,
		MessageInfos:      file_proto_deraine_proto_msgTypes,
	}.Build()
	File_proto_deraine_proto = out.File
	file_proto_deraine_proto_goTypes = nil
	file_proto_deraine_proto_depIdxs = nil
}
