// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/deraine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeraineService_WriteVector_FullMethodName  = "/deraine.v1.DeraineService/WriteVector"
	DeraineService_SearchKNN_FullMethodName    = "/deraine.v1.DeraineService/SearchKNN"
	DeraineService_DeleteVector_FullMethodName = "/deraine.v1.DeraineService/DeleteVector"
	DeraineService_GetStats_FullMethodName     = "/deraine.v1.DeraineService/GetStats"
)

// DeraineServiceClient is the client API for DeraineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeraineServiceClient interface {
	WriteVector(ctx context.Context, in *WriteVectorRequest, opts ...grpc.CallOption) (*WriteVectorResponse, error)
	SearchKNN(ctx context.Context, in *SearchKNNRequest, opts ...grpc.CallOption) (*SearchKNNResponse, error)
	DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type deraineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeraineServiceClient(cc grpc.ClientConnInterface) DeraineServiceClient {
	return &deraineServiceClient{cc}
}

func (c *deraineServiceClient) WriteVector(ctx context.Context, in *WriteVectorRequest, opts ...grpc.CallOption) (*WriteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteVectorResponse)
	err := c.cc.Invoke(ctx, DeraineService_WriteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deraineServiceClient) SearchKNN(ctx context.Context, in *SearchKNNRequest, opts ...grpc.CallOption) (*SearchKNNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKNNResponse)
	err := c.cc.Invoke(ctx, DeraineService_SearchKNN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deraineServiceClient) DeleteVector(ctx context.Context, in *DeleteVectorRequest, opts ...grpc.CallOption) (*DeleteVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVectorResponse)
	err := c.cc.Invoke(ctx, DeraineService_DeleteVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deraineServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, DeraineService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeraineServiceServer is the server API for DeraineService service.
// All implementations must embed UnimplementedDeraineServiceServer
// for forward compatibility.
type DeraineServiceServer interface {
	WriteVector(context.Context, *WriteVectorRequest) (*WriteVectorResponse, error)
	SearchKNN(context.Context, *SearchKNNRequest) (*SearchKNNResponse, error)
	DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedDeraineServiceServer()
}

// UnimplementedDeraineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeraineServiceServer struct{}

func (UnimplementedDeraineServiceServer) WriteVector(context.Context, *WriteVectorRequest) (*WriteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteVector not implemented")
}
func (UnimplementedDeraineServiceServer) SearchKNN(context.Context, *SearchKNNRequest) (*SearchKNNResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchKNN not implemented")
}
func (UnimplementedDeraineServiceServer) DeleteVector(context.Context, *DeleteVectorRequest) (*DeleteVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVector not implemented")
}
func (UnimplementedDeraineServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedDeraineServiceServer) mustEmbedUnimplementedDeraineServiceServer() {}
func (UnimplementedDeraineServiceServer) testEmbeddedByValue()                        {}

// UnsafeDeraineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeraineServiceServer will
// result in compilation errors.
type UnsafeDeraineServiceServer interface {
	mustEmbedUnimplementedDeraineServiceServer()
}

func RegisterDeraineServiceServer(s grpc.ServiceRegistrar, srv DeraineServiceServer) {
	// If the following call panics, it indicates UnimplementedDeraineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeraineService_ServiceDesc, srv)
}

func _DeraineService_WriteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).WriteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_WriteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).WriteVector(ctx, req.(*WriteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeraineService_SearchKNN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKNNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).SearchKNN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_SearchKNN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).SearchKNN(ctx, req.(*SearchKNNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeraineService_DeleteVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).DeleteVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_DeleteVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).DeleteVector(ctx, req.(*DeleteVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeraineService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeraineServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeraineService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeraineServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeraineService_ServiceDesc is the grpc.ServiceDesc for DeraineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeraineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deraine.v1.DeraineService",
	HandlerType: (*DeraineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteVector",
			Handler:    _DeraineService_WriteVector_Handler,
		},
		{
			MethodName: "SearchKNN",
			Handler:    _DeraineService_SearchKNN_Handler,
		},
		{
			MethodName: "DeleteVector",
			Handler:    _DeraineService_DeleteVector_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _DeraineService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/deraine.proto",
}
