# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import deraine_pb2 as deraine__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in deraine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeraineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteVector = channel.unary_unary(
                '/deraine.v1.DeraineService/WriteVector',
                request_serializer=deraine__pb2.WriteVectorRequest.SerializeToString,
                response_deserializer=deraine__pb2.WriteVectorResponse.FromString,
                _registered_method=True)
        self.SearchKNN = channel.unary_unary(
                '/deraine.v1.DeraineService/SearchKNN',
                request_serializer=deraine__pb2.SearchKNNRequest.SerializeToString,
                response_deserializer=deraine__pb2.SearchKNNResponse.FromString,
                _registered_method=True)
        self.DeleteVector = channel.unary_unary(
                '/deraine.v1.DeraineService/DeleteVector',
                request_serializer=deraine__pb2.DeleteVectorRequest.SerializeToString,
                response_deserializer=deraine__pb2.DeleteVectorResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/deraine.v1.DeraineService/GetStats',
                request_serializer=deraine__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=deraine__pb2.GetStatsResponse.FromString,
                _registered_method=True)


class DeraineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchKNN(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeraineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteVector': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteVector,
                    request_deserializer=deraine__pb2.WriteVectorRequest.FromString,
                    response_serializer=deraine__pb2.WriteVectorResponse.SerializeToString,
            ),
            'SearchKNN': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchKNN,
                    request_deserializer=deraine__pb2.SearchKNNRequest.FromString,
                    response_serializer=deraine__pb2.SearchKNNResponse.SerializeToString,
            ),
            'DeleteVector': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVector,
                    request_deserializer=deraine__pb2.DeleteVectorRequest.FromString,
                    response_serializer=deraine__pb2.DeleteVectorResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=deraine__pb2.GetStatsRequest.FromString,
                    response_serializer=deraine__pb2.GetStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deraine.v1.DeraineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('deraine.v1.DeraineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeraineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deraine.v1.DeraineService/WriteVector',
            deraine__pb2.WriteVectorRequest.SerializeToString,
            deraine__pb2.WriteVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchKNN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deraine.v1.DeraineService/SearchKNN',
            deraine__pb2.SearchKNNRequest.SerializeToString,
            deraine__pb2.SearchKNNResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deraine.v1.DeraineService/DeleteVector',
            deraine__pb2.DeleteVectorRequest.SerializeToString,
            deraine__pb2.DeleteVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/deraine.v1.DeraineService/GetStats',
            deraine__pb2.GetStatsRequest.SerializeToString,
            deraine__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
